mysql:
  path: '127.0.0.1'
  port: '3306'
  db-name: 'mio'
  username: 'root'
  password: '1234'
  config: ''

casbin:
  model-path: './rbac_model.conf'



jwt:
  signing-key: 'MiHoYo'
  expire-time: 604800
  buffer-time: 86400
  Issuer: 'Wei'
